name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      
    # 如果需要设置 Android SDK，需要专门的 action
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.2
        
    - name: Get project name
      id: get-project
      run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_OUTPUT
      
    - name: Clone project
      run: |
        git clone --depth=1 "${{ steps.get-project.outputs.PROJECT }}" project
        
    - name: Build APK
      working-directory: ./project
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-build-apk
        path: ./project/**/*.apk
